name: generate-ascii
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: check repo file
              run: ls

            - name: Executing shell script
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh
             